default_chart_width: int
default_chart_height: int
background_color: str
margin: float
title_color: str
title_font_family: str
title_font_size: int
title_font_char_height: int
title_font_char_width: int
title_gap: int
legend_color: str
legend_font_family: str
legend_font_size: int
legend_font_char_height: int
legend_font_char_width: int
legend_gap: int
legend_bubble_size: int
legend_bubble_offset: int
axis_title_color: str
axis_title_font_family: str
axis_title_font_size: int
axis_title_font_char_height: int
axis_title_font_char_width: int
axis_title_gap: int
tick_width: int
tick_size: int
tick_color: str
zero_color: str
label_color: str
tick_font_family: str
tick_font_size: int
tick_font_char_height: int
tick_font_char_width: int
default_series_colors: list[str]
default_dot_radius: int
default_line_width: int
default_stroke_dasharray: str
